In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn import model_selection
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.svm import SVC
import pickle

In [2]:
names=['sepal-length','sepal-width','petal-length','petal-width', 'class']
iris=pd.read_csv('IRIS.csv',names=names)
iris.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal-length    150 non-null float64
sepal-width     150 non-null float64
petal-length    150 non-null float64
petal-width     150 non-null float64
class           150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [4]:
#x=iris.iloc[:,:-1]
#y=iris.iloc[:,4]

array=iris.values
X = array[:,0:4]
Y = array[:,4]
x_train,x_test, y_train, y_test = model_selection.train_test_split(X,Y,test_size = 0.20)
print(x_train.shape)
print(x_test.shape)

(120, 4)
(30, 4)


In [12]:
#sns.pairplot(data=iris, hue='species', palette='Set2')

In [5]:
seed = 7
model = SVC()
kfold = model_selection.KFold(n_splits = 10, random_state = seed)
cv_results = model_selection.cross_val_score(model, x_train, y_train, cv = kfold, scoring = 'accuracy')
print(cv_results.mean())

0.9583333333333333


In [6]:
model.fit(x_train, y_train)
predict = model.predict(x_test)
print(accuracy_score(y_test, predict))

1.0


In [7]:
print(confusion_matrix(y_test,predict))

[[ 6  0  0]
 [ 0  9  0]
 [ 0  0 15]]


In [8]:
print(classification_report(y_test, predict))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         6
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        15

    avg / total       1.00      1.00      1.00        30



# User Input

In [12]:
x = np.array([5.1,3.5,1.4,0.2])
x=x.reshape(1,4)
p=model.predict(x)
print(x)
print(p)

[[5.1 3.5 1.4 0.2]]
['Iris-setosa']


In [20]:

pickle.dump(model, open('model.pk','wb'))
print("model saved as")

model saved as
